# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d9262be2bc360f11ce5ca2835bad3cb5d788e79c823c02d46b29040b4f010f19ba2562d48a7049741eb992c8b370e5307c06db8e2b313bf3b5d154af1acf34d

test:
  secret_key_base: 728bda6b62b00bdc4d2e7e8c2437453e0fa9c9669d84b005b13d6e39542e61e392fb89c788f6475e5bfedd7f056c5eac494066d346da3b90a4fb9f2ae9c0dc92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
